# Generated by Django 2.2.4 on 2021-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=()),
            preserve_default=False,
        ),
    ]
