# Generated by Django 2.2.4 on 2021-03-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_show_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='timestamp',
        ),
    ]
